#################################################################
###################### NexT Configuration #######################
#################################################################

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
  # sidebar: source/_data/sidebar.njk
  # footer: source/_data/footer.njk
  variable: source/_data/variables.styl
  style: source/_data/styles.styl


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

# scheme: Muse
# scheme: Mist
# scheme: Pisces
scheme: Gemini

darkmode: false

# Darkmode JS
# For more information: https://github.com/rqh656418510/hexo-next-darkmode, https://github.com/sandoche/Darkmode.js
darkmode_js:
  enable: true
  bottom: '64px' # default: '32px'
  right: 'unset' # default: '32px'
  left: '32px' # default: 'unset'
  time: '1s' # default: '0.3s'
  mixColor: 'transparent' # default: '#fff'
  backgroundColor: 'transparent' # default: '#fff'
  buttonColorDark: '#100f2c' # default: '#100f2c'
  buttonColorLight: '#fff' # default: '#fff'
  isActivated: false # default false
  saveInCookies: true # default: true
  label: '🌓' # default: ''
  autoMatchOsTheme: true # default: true
  libUrl: # Set custom library cdn url for Darkmode.js


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

creative_commons:
  license: by-nc-sa
  size: small
  sidebar: true


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  home: / || fa fa-bell

  wiki:
    default: /docs/ || fa fa-book

    Server:
      default: /server/ || fa fa-star
      outlook: /outlook.html || fa fa-eye
      players: /players.html || fa fa-users
      history: /history.html || fa fa-history

    Introduction:
      default: /introduction/ || fa fa-flag
      areas: /areas.html || fa fa-city
      commands: /commands.html || fa fa-terminal
      features: /features.html || fa fa-cogs
      rules: /rules.html || fa fa-balance-scale

    Advanced Info:
      default: /advanced-info/ || fa fa-rocket
      machines: /machines.html || fa fa-wrench
      projects: /projects.html || fa fa-tasks

    Issue: /issue.html || fa fa-bug

    # Getting Started:
    #   default: /getting-started/ || fa fa-flag
    #   Installation: /installation.html || fa fa-download
    #   Deployment: /deployment.html || fa fa-upload
    #   Configuration: /configuration.html || fa fa-wrench
    #   Upgrade: /upgrade.html || fa fa-history

    # Theme Settings:
    #   default: /theme-settings/ || fa fa-star
    #   Sidebar: /sidebar.html || fa fa-bars
    #   Footer: /footer.html || fa fa-sticky-note
    #   Posts: /posts.html || fa fa-paragraph
    #   Custom Pages: /custom-pages.html || fa fa-swatchbook
    #   Miscellaneous: /miscellaneous.html || fa fa-university
    #   SEO: /seo.html || fa fa-external-link-square-alt
    #   i18n: /internationalization.html || fa fa-language

    # Tag Plugins:
    #   default: /tag-plugins/ || fa fa-rocket
    #   Button: /button.html || fa fa-cube
    #   Caniuse: /caniuse.html || fa fa-signal
    #   Group Pictures: /group-pictures.html || fa fa-images
    #   Label: /label.html || fa fa-hat-wizard
    #   Link Grid: /link-grid.html || fa fa-grip-vertical
    #   Mermaid: /mermaid.html || fa fa-project-diagram
    #   WaveDrom: /wavedrom.html || fa fa-diagram-predecessor
    #   Note: /note.html || fa fa-adjust
    #   PDF: /pdf.html || fa fa-file-pdf
    #   Tabs: /tabs.html || fa fa-columns

    # Third Party Plugins:
    #   default: /third-party-services/ || fa fa-puzzle-piece
    #   Math Equations: /math-equations.html || fa fa-square-root-alt
    #   External Libraries: /external-libraries.html || fa fa-lightbulb
    #   Comment Systems: /comments.html || fa fa-comment-alt
    #   Post Widgets: /post-widgets.html || fa fa-gift
    #   Statistics and Analytics: /statistics-and-analytics.html || fa fa-chart-pie
    #   Search Services: /search-services.html || fab fa-algolia
    #   Chat Services: /chat-services.html || fa fa-comments

    # Advanced Settings:
    #   default: /advanced-settings/ || fa fa-cog
    #   Vendors: /vendors.html || fa fa-plug
    #   Custom Files: /custom-files.html || fa fa-palette
    #   Injects: injects.html || fa fa-layer-group
    #   Front Matter: /front-matter.html || fa fa-edit

    # Troubleshooting: /troubleshooting.html || fa fa-life-ring

  news:
    default: /news/ || 	fa fa-newspaper

  archives: /archives/ || fa fa-archive
  tags: /tags/ || fa fa-tags

  # Plugins: /plugins/ || fa fa-flask
  # sitemap: /sitemap.xml || fa fa-sitemap
  # commonweal: /404/ || fa fa-heartbeat

menu_settings:
  icons: true
  badges: true


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

favicon:
  small: /favicon-16x16-next.png
  medium: /favicon-32x32-next.png
  apple_touch_icon: /apple-touch-icon-next.png
  safari_pinned_tab: /logo.svg
  android_manifest: /manifest.json

# custom_logo: /images/custom_logo.jpg

avatar:
  url: /images/logo.png
  rounded: true

social:
  GitHub: https://github.com/MirrorTree-MC/MirrorTree || fab fa-github
  Story: http://v.bearcabbage.top/index.php/archives/30/ || fa fa-tree
  Map: http://mirror.bearcabbage.top/ || fa fa-globe-asia
  QQ Group: https://qm.qq.com/q/8YKjmjwnGU || fa fa-rss

social_icons:
  enable: true
  icons_only: false
  transition: true

toc:
  enable: true
  number: true
  wrap: true


# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2024
  icon:
    name: fa fa-heart
    animated: true
    color: "#808080"
  copyright: MirrorTree
  powered: Powered by <a href="https://hexo.io" target="_blank">Hexo</a> | Theme - <a href="https://theme-next.js.org/" target="_blank">NexT.Gemini</a>


# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

post_meta:
  categories: true
  updated_at:
    enable: true

symbols_count_time:
  separated_meta: true
  item_text_total: true

post_edit:
  enable: true
  url: https://github.com/MirrorTree-MC/MirrorTree/tree/main/source/


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

mobile_layout_economy: true

codeblock:
  theme:
    light: default
    dark: stackoverflow-dark
  copy_button:
    enable: true
    style: default

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

github_banner:
  enable: false
  permalink: https://github.com/MirrorTree-MC/MirrorTree
  title: Follow MirrorTree on GitHub

font:
  enable: true
  codes:
    external: true
    family: Inconsolata


# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

index_with_subtitle: true

exturl: true

google_site_verification: 5AUIVYTbHIAuz-eQtxSfZbWW5eg9_EVZMSQycIuXrG0


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true

# Mermaid tag
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme:
    light: default
    dark: dark

wavedrom:
  enable: true


# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

math:
  mathjax:
    enable: true
    tags: ams

pjax: true

mediumzoom: true

motion:
  async: true


# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

comments:
  lazyload: true
  active: isso

disqus:
  enable: false
  shortname: wiki-mirror-tree
  count: true

# changyan
changyan:
  enable: false
  appid: cyxBIboIr
  appkey: 953df9d73132412dc9f6fc627059d646
  count: true

# Isso
# For more information: https://isso-comments.de
isso: https://comments.mirror.bearcabbage.top/ # <data-isso>

# Gitalk
# For more information: https://gitalk.github.io
gitalk:
  enable: true
  github_id: VeriTas-arch
  repo: MirrorTree
  client_id: Ov23liMZDtuBO9zagf50
  client_secret: dbcc95df488111f20fac98defd7e6100a09b0f48
  admin_user: VeriTas-arch
  distraction_free_mode: true # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy address
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN


# ============================================================= #
# ================= Statistics and Analytics ================== #
# ============================================================= #

google_analytics:
  tracking_id: G-43861RVV8R


# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

local_search:
  enable: true
  top_n_per_article: 1


# ============================================================= #
# ======================= CDN Settings ======================== #
# ============================================================= #

vendors:
  internal: cdnjs
  plugins: cdnjs
