// This file is automatically generated using `npm run highlight`
const unavailable = ["brown-paper","brown-paper.min","cybertopia-cherry","cybertopia-cherry.min","cybertopia-dimmer","cybertopia-dimmer.min","cybertopia-icecap","cybertopia-icecap.min","cybertopia-saturated","cybertopia-saturated.min","pojoaque","pojoaque.min"];
